out = []
P = out.append
P("#! ---- the auditorium furniture (generated by m11_tail_gen.py)")
# stalls: seat rows at even y, two blocks either side of the centre aisle (x 22..25)
for y in (16, 18, 20, 22, 24, 26):
    for x in (13, 14.5, 16, 17.5, 19, 20.5, 26.5, 28, 29.5, 31, 32.5, 34):
        P(f"prop seats {x} {y} face=N")
# box fronts: gilt balustrades along the edge over the stalls
for y in list(range(12, 16)) + list(range(17, 21)) + list(range(22, 28)):
    P(f"prop balustrade 11.45 {y} yaw=90")
    P(f"prop balustrade 35.55 {y} yaw=90")
for x in list(range(12, 17)) + list(range(18, 30)) + list(range(31, 36)):
    P(f"prop balustrade {x} 27.55")
# seated guests in the stalls, facing the stage
seats = [(13,16),(16,16),(20.5,16),(28,16),(31,16),(17.5,18),(26.5,18),(32.5,18),(14.5,20),(19,20),(29.5,20),
         (13,22),(20.5,22),(28,22),(34,22),(16,24),(31,24),(19,26),(26.5,26),(32.5,26)]
for i, (x, y) in enumerate(seats):
    P(f"npc st{i+1} guest {x} {y} face=N sit evac=23,46")
open('m11_gen.txt', 'w').write("\n".join(out) + "\n")
